name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and release Morpho
    runs-on: windows-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true
      
      - name: zip Plugin
        run: |
          echo "Check"
          ls deploy
          echo "Create zip file"
          Compress-Archive -Path deploy\* -DestinationPath Morpho.zip

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}